---
# Role artifact install tasks

- name: Download Check_MK agent artifact
  include_role:
    name: amtega.artifact
  vars:
    artifact: "{{ check_mk_agent_artifact }}"
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::install
