---

- name: Download Check_MK agent artifact
  ansible.builtin.include_role:
    name: amtega.artifact
  loop: "{{ check_mk_agent_plugins_artifacts }}"
  loop_control:
    loop_var: check_mk_agent_plugin_artifact
    label: "{{ check_mk_agent_plugin_artifact.id }}"
  vars:
    artifact_defaults: >-
      {{ check_mk_agent_plugin_artifact_defaults | default({}) }}
    artifact_overrides:
      dest: "{{ check_mk_agent_plugins_dir }}"
    artifact: >-
      {{ check_mk_agent_plugin_artifact | combine(artifact_overrides) }}
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::install