---
# Role autojoin tasks

- block:
    - name: Check if host is registered
      uri:
        url: >-
          {{ check_mk_agent_server_url
             + "/check_mk/webapi.py?action=get_host&_username="
             + check_mk_agent_webapi_user
             + "&_secret="
             + check_mk_agent_webapi_password
             + "&output_format=json" }}
        method: 'POST'
        body: >-
          request={
          "hostname": "{{ check_mk_agent_autojoin_parameters.hostname }}" }
        return_content: yes
        validate_certs: "{{ check_mk_agent_autojoin_validate_certs }}"
      register: check_mk_agent_check_host_result
      check_mode: False
      changed_when: False
      failed_when: (not "json" in check_mk_agent_check_host_result)
      no_log: "{{ check_mk_agent_no_log | bool }}"

    - name: Join host to Check_MK via WebAPI
      uri:
        url: >-
         {{ check_mk_agent_server_url
            + "/check_mk/webapi.py?action=add_host&_username="
            + check_mk_agent_webapi_user
            + "&_secret="
            + check_mk_agent_webapi_password
            + "&output_format=json" }}
        method: POST
        body: >-
          request={{ check_mk_agent_autojoin_parameters | to_json }}
        return_content: yes
      when: check_mk_agent_check_host_result.json.result_code != 0
      register: check_mk_agent_join_host_result
      changed_when: ("json" in check_mk_agent_join_host_result) and
                    (check_mk_agent_join_host_result.json.result_code == 0)
      failed_when: (not "json" in check_mk_agent_join_host_result) or
                   (check_mk_agent_join_host_result.json.result_code != 0)
      no_log: "{{ check_mk_agent_no_log | bool }}"
  tags:
    - role::check_mk_agent::autojoin
