---
- name: Autojoin in check_mk site
  environment: "{{ proxy_client_environment | default({}) }}"
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::autojoin
  block:
    - name: Setup host in check_mk site
      checkmk.general.host:
        server_url: "{{ check_mk_agent_api_url }}"
        site: "{{ check_mk_agent_api_site }}"
        automation_user: "{{ check_mk_agent_api_user }}"
        automation_secret: "{{ check_mk_agent_api_password }}"
        name: "{{ check_mk_agent_autojoin_hostname }}"
        folder: "{{ check_mk_agent_autojoin_folder }}"
        state: "{{ check_mk_agent_autojoin_state }}"
        validate_certs: "{{ check_mk_agent_autojoin_validate_certs }}"
      delegate_to: "{{ check_mk_agent_autojoin_delegate_host }}"
      register: check_mk_agent_add_host_result
      no_log: "{{ check_mk_agent_no_log | default(true) }}"

    - name: Sleep to wait host register and continue
      ansible.builtin.wait_for:
        timeout: "{{ check_mk_agent_wait_for_register }}"

    - name: Discover services on host to check_mk site
      checkmk.general.discovery:
        server_url: "{{ check_mk_agent_api_url }}"
        site: "{{ check_mk_agent_api_site }}"
        automation_user: "{{ check_mk_agent_api_user }}"
        automation_secret: "{{ check_mk_agent_api_password }}"
        host_name: "{{ check_mk_agent_autojoin_hostname }}"
        state: fix_all
        validate_certs: "{{ check_mk_agent_autojoin_validate_certs }}"
      no_log: "{{ check_mk_agent_no_log | default(true) }}"
      delegate_to: "{{ check_mk_agent_autojoin_delegate_host }}"
      when: >-
        (check_mk_agent_add_host_result is changed
         or check_mk_agent_autojoin_force_discover | bool)
        and check_mk_agent_autojoin_discover | bool
        and (check_mk_agent_autojoin_state != "absent")
      register: check_mk_agent_discover_host_result

    - name: Activate changes on check_mk site
      checkmk.general.activation:
        server_url: "{{ check_mk_agent_api_url }}"
        site: "{{ check_mk_agent_api_site }}"
        automation_user: "{{ check_mk_agent_api_user }}"
        automation_secret: "{{ check_mk_agent_api_password }}"
        sites: "{{ check_mk_agent_apply_changes_sites }}"
        force_foreign_changes: >-
          {{ check_mk_agent_apply_changes_allow_foreign }}
        validate_certs: "{{ check_mk_agent_autojoin_validate_certs }}"
      no_log: "{{ check_mk_agent_no_log | default(true) }}"
      delegate_to: "{{ check_mk_agent_autojoin_delegate_host }}"
      when: >-
        (check_mk_agent_add_host_result is changed
         or check_mk_agent_discover_host_result is changed)
        and check_mk_agent_autojoin_state != "absent"
      register: check_mk_agent_activate_changes_result
      failed_when: >-
        (check_mk_agent_activate_changes_result.failed)
         and (check_mk_agent_activate_changes_result.msg
              is not search("Unauthorized: There are foreign changes"))
