---
# Role autojoin tasks

- block:
    - name: Check if host is registered
      uri:
        url: >-
          {{ check_mk_agent_webapi_url
             + "/check_mk/webapi.py?action=get_host&_username="
             + check_mk_agent_webapi_user
             + "&_secret="
             + check_mk_agent_webapi_password
             + "&output_format=json" }}
        method: 'POST'
        body: >-
          request={
          "hostname": "{{ check_mk_agent_autojoin_parameters.hostname }}" }
        return_content: yes
        validate_certs: "{{ check_mk_agent_webapi_validate_certs }}"
      register: check_mk_agent_check_host_result
      check_mode: False
      changed_when: False
      failed_when: (not "json" in check_mk_agent_check_host_result)
      no_log: "{{ check_mk_agent_no_log | bool }}"

    - name: Add host to Check_MK site via WebAPI
      uri:
        url: >-
         {{ check_mk_agent_webapi_url
            + "/check_mk/webapi.py?action=add_host&_username="
            + check_mk_agent_webapi_user
            + "&_secret="
            + check_mk_agent_webapi_password
            + "&output_format=json" }}
        method: POST
        body: >-
          request={{ check_mk_agent_autojoin_parameters | to_json }}
        return_content: yes
      when: check_mk_agent_check_host_result.json.result_code != 0
      register: check_mk_agent_add_host_result
      changed_when: ("json" in check_mk_agent_add_host_result) and
                    (check_mk_agent_add_host_result.json.result_code == 0)
      failed_when: (not "json" in check_mk_agent_add_host_result) or
                   (check_mk_agent_add_host_result.json.result_code != 0)

    - name: Discover services on host to Check_MK site via WebAPI
      uri:
        url: >-
         {{ check_mk_agent_webapi_url
            + "/check_mk/webapi.py?action=discover_services&_username="
            + check_mk_agent_webapi_user
            + "&_secret="
            + check_mk_agent_webapi_password
            + "&output_format=json" }}
        method: POST
        body: "request={{ check_mk_agent_discover_request | to_json }}"
        return_content: yes
      when: check_mk_agent_check_host_result.json.result_code != 0
      register: check_mk_agent_discover_host_result
      changed_when: ("json" in check_mk_agent_discover_host_result) and
                    (check_mk_agent_discover_host_result.json.result_code == 0)
      failed_when: (not "json" in check_mk_agent_discover_host_result) or
                   (check_mk_agent_discover_host_result.json.result_code != 0)

    - name: Activate changes on Check_MK site via WebAPI
      uri:
        url: >-
         {{ check_mk_agent_webapi_url
            + "/check_mk/webapi.py?action=activate_changes&_username="
            + check_mk_agent_webapi_user
            + "&_secret="
            + check_mk_agent_webapi_password
            + "&output_format=json" }}
        method: POST
        body: "request={{ check_mk_agent_activate_request | to_json }}"
        return_content: yes
      when: check_mk_agent_check_host_result.json.result_code != 0
      register: check_mk_agent_activate_host_result
      changed_when: ("json" in check_mk_agent_activate_host_result) and
                    ((check_mk_agent_activate_host_result.json.result_code == 0)
                      or (check_mk_agent_activate_host_result.json.result
                          is search("There are changes from other users")))
      failed_when: (not "json" in check_mk_agent_activate_host_result) or
                   ((check_mk_agent_activate_host_result.json.result_code != 0)
                     and (check_mk_agent_activate_host_result.json.result
                          is not search("There are changes from other users")))
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::autojoin
