---

- block:
    - name: Ensure host is not registered
      uri:
        url: '{{ check_mk_agent_server_url }}/check_mk/webapi.py?action=get_host&_username={{ check_mk_agent_webapi_user }}&_secret={{ check_mk_agent_webapi_password }}&output_format=json'
        method: 'POST'
        body: 'request={ "hostname": "{{ check_mk_agent_autojoin_hostname }}" }'
        return_content: yes
      register: check_mk_agent_get_host_result
      check_mode: False
      changed_when: False
      failed_when: (not "json" in check_mk_agent_get_host_result)

    - name: Add host to Check_MK site via WebAPI
      uri:
        url: '{{ check_mk_agent_server_url }}/check_mk/webapi.py?action=add_host&_do_confirm=yes&_username={{ check_mk_agent_webapi_user }}&_secret={{ check_mk_agent_webapi_password }}&output_format=json'
        method: 'POST'
        body: 'request={ "hostname": "{{ check_mk_agent_autojoin_hostname  }}", "folder": "{{ check_mk_agent_autojoin_folder }}" }'
        return_content: yes
      when: '{{ check_mk_agent_get_host_result.json.result == "No such host" }}'
      register: check_mk_agent_add_host_result
      changed_when: ("json" in check_mk_agent_add_host_result) and
                    (check_mk_agent_add_host_result.json.result_code == 0)
      failed_when: (not "json" in check_mk_agent_add_host_result) or
                   (check_mk_agent_add_host_result.json.result_code != 0)

    - name: Send notification email
      mail:
        from: "{{ ANSIBLE_MAIL_FROM }}"
        subject: Alta de host en check_mk
        to: "{{ check_mk_agent_autojoin_notification_email }}"
        body: "{{ lookup('template', 'autojoin.j2') }}"
        username: "{{ ANSIBLE_USER }}"
        password:  "{{ ANSIBLE_PASSWORD }}"
        host: "{{ ANSIBLE_MAIL_SMTP_SERVER }}"
        port: "{{ ANSIBLE_MAIL_SMTP_SERVER_PORT }}"
        secure: "{{ ANSIBLE_MAIL_SECURE }}"
      when: check_mk_agent_autojoin_notification_email is defined
      no_log: yes
  tags:
    - role::check_mk_agent::autojoin
