---

- name: Gather check_mk facts
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::facts
  block:
    - name: Gather check_mk agent directory
      ansible.builtin.shell: >-
        set -o pipefail ;
        /usr/bin/check_mk_agent
        | head -n 10
        | grep AgentDirectory
        | awk '{ print $NF }'
      changed_when: no
      register: check_mk_agent_dir_result

    - name: Gather check_mk agent plugins directory
      ansible.builtin.shell: >-
        set -o pipefail ;
        /usr/bin/check_mk_agent
        | head -n 10
        | grep PluginsDirectory
        | awk '{ print $NF }'
      changed_when: no
      register: check_mk_agent_plugins_dir_result

    - name: Setup fact with changes application result
      ansible.builtin.set_fact:
        check_mk_agent_dir: "{{ check_mk_agent_dir_result.stdout }}"

        check_mk_agent_plugins_dir: >-
          {{ check_mk_agent_plugins_dir_result.stdout }}

        check_mk_agent_host_added: >-
          {{ check_mk_agent_add_host_result | default({}) is changed }}

        check_mk_agent_services_changed: >-
          {{ check_mk_agent_discover_host_result | default({}) is changed }}

        check_mk_agent_services_changes_applied: >-
          {{ check_mk_agent_activate_changes_result | default({}) is changed }}