---

- name: Setup fact with changes application result
  set_fact:
    check_mk_agent_host_added: >-
      {{ check_mk_agent_add_host_result | default({}) is changed }}
    check_mk_agent_services_changed: >-
      {{ check_mk_agent_discover_host_result | default({}) is changed }}
    check_mk_agent_services_changes_applied: >-
      {{ check_mk_agent_activate_changes_result | default({}) is changed }}
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::facts
