---

- name: Install check_mk
  block:
    - name: Get installed check_mk agent version
      ansible.builtin.shell: >-
        /usr/bin/check_mk_agent | grep '[V]ersion' | awk {'print $2'}
      args:
        warn: no
      changed_when: no
      failed_when: no
      register: check_mk_agent_version_result

    - name: Install check_mk from artifact
      when: check_mk_agent_artifact is defined
      block:
        - name: Gather available artifacts
          ansible.builtin.uri:
            url: >-
              {{ check_mk_agent_artifact.host
                 + "/"
                 + check_mk_agent_artifact.path }}
            return_content: yes
            validate_certs: >-
              {{ check_mk_agent_artifact.validate_certs | default(true) }}
          register: check_mk_agent_get_artifacts_result
          environment: "{{ proxy_client_environment | default({}) }}"

        - name: Setup check_mk artifact
          include_tasks: artifact_agent.yml
          when: >-
              not (check_mk_agent_version_to_install | default("0"))
              is version(check_mk_agent_installed_version, "==")

    - name: Install check_mk package
      include_tasks: "install_package_{{ ansible_facts.pkg_mgr }}.yml"
      when:
        - >-
          not (check_mk_agent_version_to_install | default("0"))
          is version(check_mk_agent_installed_version, "==")
          or check_mk_agent_version_result.stdout | length == 0

    - name: Get installed check_mk agent version after install
      ansible.builtin.shell: >-
        set -o pipefail ;
        /usr/bin/check_mk_agent | grep '[V]ersion' | awk {'print $2'}
      changed_when: no
      register: check_mk_agent_version_result

    - name: Remove check_mk agent artifact
      ansible.builtin.file:
        path: "{{ check_mk_agent_package }}"
        state: absent
      when: check_mk_agent_artifact is defined

    - name: Setup check_mk agent facts
      include_tasks: facts.yml

    - name: Setup check_mk plugins artifacts
      include_tasks: artifact_plugins.yml
      when: check_mk_agent_plugins_artifacts | default([]) | length > 0

    - when: ansible_facts.distribution_major_version is version("8", "<")
      include_tasks: xinetd.yml

    - name: Remove check_mk xinetd sample caching agent service
      ansible.builtin.file:
        path: /etc/xinetd.d/check-mk-caching-agent
        state: absent
  vars:
    check_mk_agent_installed_version: >-
      {{ check_mk_agent_version_result.stdout_lines.0 | default("0") }}

    check_mk_agent_package: >-
      {{ (check_mk_agent_artifact is defined)
         | ternary((artifact_result
                    [check_mk_agent_artifact.id | default("")]
                    | default({})).download_path
                   | default(""),
                   (check_mk_agent_version is defined)
                   | ternary("check-mk-agent-"
                             + check_mk_agent_version | default("0"),
                             "check-mk-agent")) }}
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::install