---

- block:
    - name: Get installed Check_MK agent version
      shell: >-
        /usr/bin/check_mk_agent | grep '[V]ersion' | awk {'print $2'}
      args:
        warn: no
      changed_when: no
      failed_when: no
      register: check_mk_agent_version_result

    - name: Setup Check_MK artifact
      include: artifact_agent.yml
      when:
        - check_mk_agent_artifact is defined
        - >-
          not (check_mk_agent_version | default("0"))
          is version(check_mk_agent_installed_version, "==")

    - name: Install Check_MK package
      include_tasks: "install_package_{{ ansible_facts.pkg_mgr }}.yml"

    - name: Get installed Check_MK agent version after install
      shell: >-
        set -o pipefail ;
        /usr/bin/check_mk_agent | grep '[V]ersion' | awk {'print $2'}
      changed_when: no
      register: check_mk_agent_version_result

    - name: Remove Check_MK agent artifact
      file:
        path: "{{ check_mk_agent_package }}"
        state: absent
      when: check_mk_agent_artifact is defined

    - name: Setup Check_MK agent facts
      include_tasks: facts.yml

    - name: Setup Check_MK plugins artifacts
      include: artifact_plugins.yml
      when: check_mk_agent_plugins_artifacts | default([]) | length > 0

    - when: >-
        (ansible_facts.distribution | lower in ["centos", "redhat"]
         and ansible_facts.distribution_major_version is version("8", "<"))
        or (ansible_facts.distribution | lower == "fedora"
            and ansible_facts.distribution_major_version is version("34", "<"))
      include: xinetd.yml

    - name: Remove Check_MK xinetd sample caching agent service
      file:
        path: /etc/xinetd.d/check-mk-caching-agent
        state: absent
  vars:
    check_mk_agent_installed_version: >-
      {{ check_mk_agent_version_result.stdout_lines.0 | default("0") }}

    check_mk_agent_package: >-
      {{ (check_mk_agent_artifact is defined)
         | ternary((artifact_result
                    [check_mk_agent_artifact.id | default("")]
                    | default({})).download_path
                   | default(""),
                   (check_mk_agent_version is defined)
                   | ternary("check-mk-agent-"
                             + check_mk_agent_version | default("0"),
                             "check-mk-agent")) }}
  tags:
    - role::check_mk_agent
    - role::check_mk_agent::install
