---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6

- include_role:
    name: amtega.epel
  when: not check_mk_agent_artifact is defined

- block:

    - include_tasks: install.yml

    - include_tasks: autojoin.yml
      when: check_mk_agent_autojoin

  tags:
    - role::check_mk_agent
