---
# Role tasks

- block:
    - include_tasks: install.yml
      tags:
        - role::check_mk_agent::install

    - include_tasks: autojoin.yml
      when: check_mk_agent_autojoin
      tags:
        - role::check_mk_agent::autojoin

    - include_tasks: facts.yml
      tags:
        - role::check_mk_agent::facts
  tags:
    - role::check_mk_agent
