---
- name: Setup check_mk
  tags:
    - role::check_mk_agent
  block:
    - name: Install check_mk agent
      ansible.builtin.include_tasks: install.yml
      tags:
        - role::check_mk_agent::install

    - name: Autojoin check_mk agent
      ansible.builtin.include_tasks: autojoin.yml
      when: check_mk_agent_autojoin | bool
      tags:
        - role::check_mk_agent::autojoin
