---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
driver:
  name: podman
lint: ${MOLECULE_SCENARIO_DIRECTORY}/linters.sh
platforms:
  - name: centos7-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:centos7
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: centos8-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:stream8
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ansible_user: root
          check_mk_agent_autojoin: true
          check_mk_agent_no_log: false
          check_mk_agent_autojoin_attributes:
            labels:
              provisioner: ansible
              category: test
      molecule_hosts_centos_8:
        vars:
          ansible_python_interpreter: /usr/bin/python3
      molecule_hosts_centos_7:
        vars:
          ansible_python_interpreter: /usr/bin/python3
          check_mk_agent_autojoin_delegate_host: localhost
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
