---
- name: Verify
  hosts: molecule_hosts
  gather_facts: true
  tasks:
    - name: Verify distros with version < 8
      when: ansible_facts.distribution_major_version is version("8", "<")
      block:
        - name: Cat command
          ansible.builtin.command: cat /etc/xinetd.d/check-mk-agent
          changed_when: false
          register: command_output

        - name: Check_mk configuration status in xinetd
          ansible.builtin.assert:
            quiet: true
            that: >-
              command_output.stdout
              is search("server.*=.*/usr/bin/check_mk_agent")

    - name: Verify distros with version >= 8
      when: ansible_facts.distribution_major_version is version("8", ">=")
      block:
        - name: Cat command
          ansible.builtin.command: cat /etc/systemd/system/check_mk@.service
          changed_when: false
          register: command_output

        - name: Check_mk configuration status in systemd
          ansible.builtin.assert:
            quiet: true
            that: >-
              command_output.stdout
              is search("ExecStart=.*/usr/bin/check_mk_agent")

    - name: Gather check_mk agent plugins directory
      ansible.builtin.shell: >-
        set -o pipefail ;
        /usr/bin/check_mk_agent
        | head -n 10
        | grep PluginsDirectory
        | awk '{ print $NF }'
      changed_when: false
      register: plugins_dir_result

    - name: Check plugins
      ansible.builtin.stat:
        path: "{{ plugins_dir_result.stdout }}/{{ item.file }}"
      register: stat_result
      loop: "{{ check_mk_agent_plugins_artifacts | default([]) }}"

    - name: Assert plugins are installed
      ansible.builtin.assert:
        quiet: true
        that: >-
          stat_result.results
          | selectattr("stat.exists", "equalto", false)
          | list
          | length == 0
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}
